Repository catalyst-team/catalyst, pull requests merged in 2019-10, with the labels that each got.

#381 fix - AccuracyCallback for multi-label classification
  catalyst/dl/callbacks/metrics/accuracy.py
  catalyst/dl/utils/criterion/accuracy.py
Labels: bug

#397 Implement per phase loader params
  catalyst/dl/experiment/config.py
  examples/_tests_mnist_stages/config1.yml
Labels: WIP, enhancement

#396 Add checkpoints 16+mb support to MongoDB
  catalyst/__version__.py
  catalyst/rl/db/mongo.py
Labels: WIP, enhancement

#441 fix FP16 mode
  .github/PULL_REQUEST_TEMPLATE.md
  examples/notebooks/segmentation-tutorial.ipynb
Labels: enhancement

#443 Loggers logic out of `RunnerState`
  catalyst/dl/callbacks/__init__.py
  catalyst/dl/callbacks/checkpoint.py
  catalyst/dl/callbacks/logging.py
  catalyst/dl/callbacks/misc.py
  catalyst/dl/core/__init__.py
  catalyst/dl/core/callback.py
  catalyst/dl/core/runner.py
  catalyst/dl/core/state.py
  catalyst/dl/experiment/base.py
  catalyst/dl/experiment/config.py
  catalyst/dl/experiment/supervised.py
  catalyst/dl/runner/__init__.py
  catalyst/dl/runner/supervised.py
  catalyst/dl/utils/__init__.py
  catalyst/dl/utils/callbacks.py
  catalyst/utils/compression.py
  catalyst/utils/serialization.py
Labels: enhancement
