Repository catalyst-team/catalyst, pull requests merged in 2019-12, with the labels that each got.

#535 added weighted sum
  catalyst/data/augmentor.py
  catalyst/dl/callbacks/criterion.py
  catalyst/utils/dataset.py
  catalyst/utils/initialization.py
  catalyst/utils/registry.py
  examples/notebooks/classification-tutorial.ipynb
  examples/notebooks/segmentation-tutorial.ipynb
Labels: enhancement

#510 Update supervised.py
  catalyst/dl/runner/supervised.py
Labels: enhancement, good first issue

#533 Add classwise iou callback
  catalyst/dl/__init__.py
  catalyst/dl/callbacks/__init__.py
  catalyst/dl/callbacks/metrics/__init__.py
  catalyst/dl/callbacks/metrics/iou.py
  catalyst/dl/tests/test_iou.py
  catalyst/dl/utils/criterion/iou.py
Labels: WIP, enhancement

#540 DistilBERT text classification pipeline
  .gitignore
  .travis.yml
  README.md
  bin/tests/check_dl.sh
  bin/tests/check_nlp.sh
  catalyst/contrib/criterion/__init__.py
  catalyst/contrib/criterion/ce.py
  catalyst/contrib/criterion/center.py
  catalyst/contrib/criterion/contrastive.py
  catalyst/contrib/criterion/dice.py
  catalyst/contrib/criterion/huber.py
  catalyst/contrib/criterion/iou.py
  catalyst/contrib/criterion/wing.py
  catalyst/contrib/models/nlp/__init__.py
  catalyst/contrib/models/nlp/bert/__init__.py
  catalyst/contrib/models/nlp/bert/distil_classify.py
  catalyst/data/nlp/__init__.py
  catalyst/data/nlp/classify.py
  catalyst/data/nlp/tests/__init__.py
  catalyst/data/nlp/tests/test_text_clf_dataset.py
  catalyst/dl/runner/supervised.py
  catalyst/dl/scripts/run.py
  catalyst/dl/scripts/trace.py
  docs/index.rst
  examples/README.md
  examples/_tests_distilbert_text_classification/README.md
  examples/_tests_distilbert_text_classification/config1_basic.yml
  examples/_tests_distilbert_text_classification/config2_small_max_seq_length.yml
  examples/_tests_distilbert_text_classification/input/train.csv
  examples/_tests_distilbert_text_classification/input/valid.csv
  examples/distilbert_text_classification/README.md
  examples/distilbert_text_classification/__init__.py
  examples/distilbert_text_classification/config.yml
  examples/distilbert_text_classification/experiment.py
  examples/distilbert_text_classification/input/train.csv
  examples/distilbert_text_classification/input/valid.csv
  requirements/requirements-dev.txt
  requirements/requirements-nlp.txt
  setup.cfg
  setup.py
Labels: enhancement

#547 Fix bug in tensorflow versions comparison
  catalyst/utils/seed.py
Labels: enhancement, good first issue

#542 Fix bug when an exception is suppressed
  catalyst/dl/core/runner.py
Labels: bug, good first issue

#551 added Ralamb
  catalyst/contrib/optimizers/__init__.py
  catalyst/contrib/optimizers/ralamb.py
  examples/cifar_stages/config.yml
Labels: enhancement

#550 Added samplers_params
  catalyst/contrib/registry.py
  catalyst/dl/experiment/config.py
  catalyst/dl/registry.py
  examples/cifar_stages/config.yml
  examples/configs/config-description-eng.yml
  examples/configs/config-description-rus.yml
Labels: enhancement

#569 Make f1 faster and work properly for masks
  catalyst/dl/core/callback.py
  catalyst/dl/meters/ppv_tpr_f1_meter.py
  catalyst/dl/tests/test_ppv_tpr_f1.py
Labels: WIP

#508 Update ce.py
  bin/tests/check_dl.sh
  catalyst/contrib/criterion/__init__.py
  catalyst/contrib/criterion/ce.py
  examples/_tests_mnist_stages/config6.yml
Labels: WIP, enhancement, good first issue

#568 `tag2label` add `--recursive`
  catalyst/contrib/scripts/tag2label.py
  catalyst/utils/dataset.py
Labels: WIP
