Repository catalyst-team/catalyst, pull requests merged in 2020-08, with the labels that each got.

#893 Feature: TPU support
  CHANGELOG.md
  catalyst/contrib/dl/callbacks/tests/test_gradnorm_logger.py
  catalyst/contrib/dl/callbacks/tests/test_tracer_callback.py
  catalyst/core/callbacks/checkpoint.py
  catalyst/core/callbacks/control_flow.py
  catalyst/core/callbacks/optimizer.py
  catalyst/core/runner.py
  catalyst/tools/settings.py
  catalyst/utils/checkpoint.py
  catalyst/utils/components.py
  catalyst/utils/torch.py
  requirements/requirements-cv.txt
  requirements/requirements.txt
Labels: WIP

#894 Pruning
  catalyst/core/callbacks/__init__.py
  catalyst/core/callbacks/pruning.py
  catalyst/core/callbacks/tests/test_pruning.py
  catalyst/tools/settings.py
  catalyst/utils/__init__.py
  catalyst/utils/initialization.py
  catalyst/utils/pruning.py
Labels: WIP, enhancement

#907 Fix: config API - autoresume & resume
  CHANGELOG.md
  bin/tests/check_dl_core_callbacks.sh
  catalyst/core/callbacks/checkpoint.py
  catalyst/dl/experiment/config.py
Labels: bug
