Repository catalyst-team/catalyst, pull requests merged in 2020-01, with the labels that each got.

#577 logger not set ConsoleLogger, TensorboardLogger error
  catalyst/dl/callbacks/logging.py
Labels: bug

#589 Margin & Triplet loss once again
  catalyst/contrib/criterion/functional.py
  catalyst/contrib/criterion/margin.py
  catalyst/contrib/criterion/triplet.py
Labels: WIP, enhancement

#597 Teamcity continuous integration system(instead of Travis)
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  README.md
  bin/_check_codestyle.sh
  bin/flake8.sh
  bin/tests/check_ddpg.sh
  bin/tests/check_dl.sh
  bin/tests/check_dqn.sh
  bin/tests/check_nlp.sh
  bin/tests/check_ppo.sh
  bin/tests/check_reinforce.sh
  bin/tests/check_sac.sh
  bin/tests/check_td3.sh
  bin/yapf.sh
  catalyst/utils/config.py
  docker/Dockerfile-teamcity
  docs/index.rst
  requirements/requirements-rl.txt
  teamcity/ddpg.sh
  teamcity/deploy.sh
  teamcity/dqn.sh
  teamcity/examples.sh
  teamcity/ppo.sh
  teamcity/reinforce.sh
  teamcity/sac.sh
  teamcity/td3.sh
  teamcity/tests.sh
Labels: enhancement

#595 ConfigAPI add transform_params
  bin/_check_codestyle.sh
  catalyst/data/__init__.py
  catalyst/data/augmentor.py
  catalyst/data/reader.py
  catalyst/dl/experiment/config.py
  catalyst/dl/registry.py
  catalyst/utils/registry.py
  examples/_tests_mnist_stages2/__init__.py
  examples/_tests_mnist_stages2/config1.yml
  examples/_tests_mnist_stages2/config2.yml
  examples/_tests_mnist_stages2/config3.yml
  examples/_tests_mnist_stages2/config_finder.yml
  examples/_tests_mnist_stages2/config_fp16_O1.yml
  examples/_tests_mnist_stages2/config_fp16_O2.yml
  examples/_tests_mnist_stages2/config_fp16_O3.yml
  examples/_tests_mnist_stages2/experiment.py
  examples/_tests_mnist_stages2/transform.py
  examples/cifar_stages/__init__.py
  examples/cifar_stages/config.yml
  examples/cifar_stages/experiment.py
  examples/cifar_stages/model.py
  teamcity/deploy.sh
  teamcity/examples.sh
  teamcity/tests.sh
Labels: enhancement
