Repository catalyst-team/catalyst, pull requests merged in 2020-06, with the labels that each got.

#829 fix: added missed dashes in docker perfixes #828
  .github/workflows/deploy.yml
  CHANGELOG.md
Labels: bug

#830 feat: add mergify
  .github/workflows/codestyle.yml
  .github/workflows/dl_cpu_core.yml
  .github/workflows/dl_cpu_cv.yml
  .github/workflows/dl_cpu_nlp.yml
  .github/workflows/pr_lint.yml
Labels: WIP

#844 feat: add docs build on push to master branch
  .github/workflows/deploy_publish.yml
  .github/workflows/deploy_push.yml
  CHANGELOG.md
Labels: docs

#845 fix: dependabot confg contained invalid details #781
  .dependabot/config.yml
  CHANGELOG.md
Labels: bug

#839 Hyper Parameters
  CHANGELOG.md
  catalyst/core/experiment.py
  catalyst/dl/experiment/config.py
  catalyst/dl/experiment/experiment.py
  catalyst/dl/experiment/tests/test_supervised.py
Labels: WIP, enhancement

#859 fix: links in docstrings
  catalyst/contrib/data/transforms.py
  catalyst/contrib/nn/criterion/circle.py
  catalyst/contrib/nn/criterion/triplet.py
  catalyst/contrib/nn/modules/se.py
  catalyst/data/sampler.py
  catalyst/utils/torch.py
Labels: docs

#842 Feature: wrapper for callbacks
  CHANGELOG.md
  bin/tests/check_dl_core_wrapper_callback.sh
  catalyst/contrib/dl/callbacks/periodic_loader_callback.py
  catalyst/core/callback.py
  catalyst/core/callbacks/__init__.py
  catalyst/core/callbacks/wrapper.py
  catalyst/dl/experiment/config.py
  catalyst/dl/experiment/experiment.py
  catalyst/dl/experiment/supervised.py
  catalyst/dl/utils/__init__.py
  catalyst/dl/utils/callbacks.py
  docs/api/core.rst
  tests/_tests_dl_callbacks/config21.yml
  tests/_tests_dl_callbacks/config22.yml
  tests/_tests_dl_callbacks/config23.yml
  tests/_tests_dl_callbacks/config24.yml
  tests/_tests_dl_callbacks/config25.yml
  tests/_tests_dl_callbacks/config26.yml
  tests/_tests_dl_callbacks/config27.yml
  tests/_tests_dl_callbacks/config28.yml
  tests/_tests_dl_callbacks/config29.yml
  tests/_tests_scripts/core_wrapper.py
Labels: enhancement

#864 fix: update docs deploy action
  .github/workflows/deploy_push.yml
  CHANGELOG.md
Labels: docs

#825 Feature: Sampling triplets inside the batch
  CHANGELOG.md
  catalyst/data/sampler.py
  catalyst/data/sampler_inbatch.py
  catalyst/data/tests/test_sampler.py
  catalyst/data/tests/test_sampler_inbatch.py
  catalyst/utils/torch.py
Labels: WIP

#866 fix: push gh-pages dir with docs
  .github/workflows/deploy_push.yml
Labels: docs
