Repository catalyst-team/catalyst, pull requests merged in 2020-04, with the labels that each got.

#753 fix docker
  docker/Dockerfile
  docker/Dockerfile-dev
  docker/Dockerfile-dev-fp16
  docker/Dockerfile-fp16
  docker/Dockerfile-teamcity
Labels: enhancement

#679 [WIP] Fixed gradient tracking
  .gitignore
  catalyst/contrib/dl/callbacks/__init__.py
  catalyst/contrib/dl/callbacks/optimizer.py
  catalyst/contrib/dl/callbacks/tests/__init__.py
  catalyst/contrib/dl/callbacks/tests/test_optimizer_callback.py
  catalyst/core/callbacks/optimizer.py
Labels: WIP, enhancement

#771 add dependabot
  .dependabot/config.yml
Labels: dependencies

#766 Add method "detach" in utils to address issue #758
  catalyst/utils/__init__.py
  catalyst/utils/torch.py
  examples/notebooks/segmentation-tutorial.ipynb
Labels: bug, enhancement

#749 Fix division by zero
  catalyst/core/callbacks/timer.py
Labels: bug
